//
//  TorrentField.swift
//  Transmission
//
//  Created by Federico Arvat on 26/07/23.
//

import Foundation

public enum TorrentField {
	public static let activityDate = "activityDate"
	public static let addedDate = "addedDate"
	public static let availability = "availability"
	public static let bandwidthPriority = "bandwidthPriority"
	public static let comment = "comment"
	public static let corruptEver = "corruptEver"
	public static let creator = "creator"
	public static let dateCreated = "dateCreated"
	public static let desiredAvailable = "desiredAvailable"
	public static let doneDate = "doneDate"
	public static let downloadDir = "downloadDir"
	public static let downloadedEver = "downloadedEver"
	public static let downloadLimit = "downloadLimit"
	public static let downloadLimited = "downloadLimited"
	public static let editDate = "editDate"
	public static let error = "error"
	public static let errorString = "errorString"
	public static let eta = "eta"
	public static let etaIdle = "etaIdle"
	public static let file = "file"
	public static let files = "files"
	public static let fileStats = "fileStats"
	public static let group = "group"
	public static let hashString = "hashString"
	public static let haveUnchecked = "haveUnchecked"
	public static let haveValid = "haveValid"
	public static let honorsSessionLimits = "honorsSessionLimits"
	public static let id = "id"
	public static let isFinished = "isFinished"
	public static let isPrivate = "isPrivate"
	public static let isStalled = "isStalled"
	public static let labels = "labels"
	public static let leftUntilDone = "leftUntilDone"
	public static let magnetLink = "magnetLink"
	public static let manualAnnounceTime = "manualAnnounceTime"
	public static let maxConnectedPeers = "maxConnectedPeers"
	public static let metadataPercentComplete = "metadataPercentComplete"
	public static let name = "name"
	public static let peer = "peer"
	public static let peers = "peers"
	public static let peersConnected = "peersConnected"
	public static let peersFrom = "peersFrom"
	public static let peersGettingFromUs = "peersGettingFromUs"
	public static let peersSendingToUs = "peersSendingToUs"
	public static let percentComplete = "percentComplete"
	public static let percentDone = "percentDone"
	public static let pieces = "pieces"
	public static let pieceCount = "pieceCount"
	public static let pieceSize = "pieceSize"
	public static let priorities = "priorities"
	public static let primary = "primary"
	public static let queuePosition = "queuePosition"
	public static let rateDownload = "rateDownload"
	public static let rateUpload = "rateUpload"
	public static let recheckProgress = "recheckProgress"
	public static let secondsDownloading = "secondsDownloading"
	public static let secondsSeeding = "secondsSeeding"
	public static let seedIdleLimit = "seedIdleLimit"
	public static let seedIdleMode = "seedIdleMode"
	public static let seedRatioLimit = "seedRatioLimit"
	public static let seedRatioMode = "seedRatioMode"
	public static let sequentialDownload = "sequentialDownload"
	public static let sizeWhenDone = "sizeWhenDone"
	public static let startDate = "startDate"
	public static let status = "status"
	public static let trackers = "trackers"
	public static let trackerList = "trackerList"
	public static let trackerStats = "trackerStats"
	public static let totalSize = "totalSize"
	public static let torrentFile = "torrentFile"
	public static let uploadedEver = "uploadedEver"
	public static let uploadLimit = "uploadLimit"
	public static let uploadLimited = "uploadLimited"
	public static let uploadRatio = "uploadRatio"
	public static let wanted = "wanted"
	public static let webseeds = "webseeds"
	public static let webseedsSendingToU = "webseedsSendingToU"
}
