//
//  SessionField.swift
//  Transmission
//
//  Created by Federico Arvat on 22/08/23.
//

import Foundation

public enum SessionField {
	public static let altSpeedDown = "alt-speed-down"
	public static let altSpeedEnabled = "alt-speed-enabled"
	public static let altSpeedTimeBegin = "alt-speed-time-begin"
	public static let altSpeedTimeDay = "alt-speed-time-day"
	public static let altSpeedTimeEnabled = "alt-speed-time-enabled"
	public static let altSpeedTimeEnd = "alt-speed-time-end"
	public static let altSpeedUp = "alt-speed-up"
	public static let blocklistEnabled = "blocklist-enabled"
	public static let blocklistSize = "blocklist-size"
	public static let blocklistUrl = "blocklist-url"
	public static let cacheSizeMb = "cache-size-mb"
	public static let configDir = "config-dir"
	public static let defaultTrackers = "default-trackers"
	public static let dhtEnabled = "dht-enabled"
	public static let downloadDir = "download-dir"
	public static let downloadDirFreeSpace = "download-dir-free-space"
	public static let downloadQueueEnabled = "download-queue-enabled"
	public static let downloadQueueSize = "download-queue-size"
	public static let encryption = "encryption"
	public static let idleSeedingLimitEnabled = "idle-seeding-limit-enabled"
	public static let idleSeedingLimit = "idle-seeding-limit"
	public static let incompleteDirEnabled = "incomplete-dir-enabled"
	public static let incompleteDir = "incomplete-dir"
	public static let lpdEnabled = "lpd-enabled"
	public static let peerLimitGlobal = "peer-limit-global"
	public static let peerLimitPerTorrent = "peer-limit-per-torrent"
	public static let peerPortRandomOnStart = "peer-port-random-on-start"
	public static let peerPort = "peer-port"
	public static let pexEnabled = "pex-enabled"
	public static let portForwardingEnabled = "port-forwarding-enabled"
	public static let queueStalledEnabled = "queue-stalled-enabled"
	public static let queueStalledMinutes = "queue-stalled-minutes"
	public static let renamePartialFiles = "rename-partial-files"
	public static let rpcVersionMinimum = "rpc-version-minimum"
	public static let rpcVersionSemver = "rpc-version-semver"
	public static let rpcVersion = "rpc-version"
	public static let scriptTorrentAddedEnabled = "script-torrent-added-enabled"
	public static let scriptTorrentAddedFilename = "script-torrent-added-filename"
	public static let scriptTorrentDoneEnabled = "script-torrent-done-enabled"
	public static let scriptTorrentDoneFilename = "script-torrent-done-filename"
	public static let scriptTorrentDoneSeedingEnabled = "script-torrent-done-seeding-enabled"
	public static let scriptTorrentDoneSeedingFilename = "script-torrent-done-seeding-filename"
	public static let seedQueueEnabled = "seed-queue-enabled"
	public static let seedQueueSize = "seed-queue-size"
	public static let seedRatioLimit = "seedRatioLimit"
	public static let seedRatioLimited = "seedRatioLimited"
	public static let sessionId = "session-id"
	public static let speedLimitDownEnabled = "speed-limit-down-enabled"
	public static let speedLimitDown = "speed-limit-down"
	public static let speedLimitUpEnabled = "speed-limit-up-enabled"
	public static let speedLimitUp = "speed-limit-up"
	public static let startAddedTorrents = "start-added-torrents"
	public static let trashOriginalTorrentFiles = "trash-original-torrent-files"
	public static let units = "units"
	public static let utpEnabled = "utp-enabled"
	public static let version = "version"
}
